### PR TITLE
Add support for Symfony 7

### PR DESCRIPTION
**Pull request by kristoftorfs**
This pull request adds support for Symfony 7.

### CODE REVIEW

**Review by Ciloe — APPROVED** [review]

**Review by localheinz — CHANGES_REQUESTED** [review]
The tests are failing, @kristoftorfs - can you adjust?

**Comment by kristoftorfs** [comment]
@localheinz Tests should be fixed now.

**Review by Ciloe — APPROVED** [review]

**Comment by Ciloe** [comment]
Many thanks for your help ! @localheinz It's passing now

**Review by localheinz — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @Ciloe and @kristoftorfs!

**Pull request merged**
