### PR TITLE
Fix // and ** operator order

### PR DESCRIPTION
**Pull request by Dodenis**
When using the Math operator "//" we get the error: `ERROR There should be 1 space between the" / "operator and its right operand.` because "//" was specified after "/" in RulesetBuilder

### CODE REVIEW

**Review by Ciloe — CHANGES_REQUESTED** [review]
Thanks a lot, can you add a test please ?

**Comment by Dodenis** [comment]
Yes of course

**Review by Ciloe — APPROVED** [review]

**Comment by Dodenis** [comment]
I take this "PR" to add the fix for issue #135, which is the same fix

**Review by Ciloe — APPROVED** [review]
I Think you can check for other operators ?

**Comment by Dodenis** [comment]
This is what I did, I didn't see any other definition order problems

**Comment by OwlyCode** [comment]
Looks good to me!

**Review by OwlyCode — APPROVED** [review]

**Comment by OwlyCode** [comment]
Thank you @Dodenis!

**Pull request merged**
