### PR TITLE
add excluded directories

### LINKED ISSUE #74: New optional parameter: excluded directories
Allow excluding directories (like: .git, .npm, etc.) from file scanning with a new optional parameter.

https://github.com/friendsoftwig/twigcs/blob/v3.1.3/src/Console/LintCommand.php#L37-L38

### PR DESCRIPTION
**Pull request by oallain**
Fixes #74 

We can now optionally exclude :

No exclusion :
```
vendor/bin/twigcs templates/
```
One exclusion
```
vendor/bin/twigcs templates/ --exclude dir1
```
or multiples exclude like :

```
vendor/bin/twigcs templates/ --exclude dir1 --exclude dir2
```

### CODE REVIEW

**Review by Ciloe — CHANGES_REQUESTED** [review]
Can you add some tests ? Thanks !

**Comment by OwlyCode** [comment]
We do not have tests for the command at the moment. @oallain will you need some help on that?

**Review by OwlyCode — APPROVED** [review]
Awesome, thank you!

**Comment by oallain** [comment]
Wow merged too fast @OwlyCode :heart_eyes: 

@Ciloe job done :smile:

**Pull request merged**
